document.writeln('<meta charset="utf-8">');
document.writeln('<meta http-equiv="X-UA-Compatible" content="IE=edge">');
document.writeln('<meta name="viewport" content="width=device-width, initial-scale=1">');
document.writeln('<title>2018 World Cup</title>');
document.writeln('<link rel="SHORTCUT ICON" href="images/football.ico"/>');
document.writeln('<link href="css/bootstrap.min.css" rel="stylesheet">');
document.writeln('<style type="text/css"> ');
document.writeln('.clear-padding{');
document.writeln('	padding:0;');
document.writeln('}');
document.writeln('.clear-padding-row{');
document.writeln('	padding-left:0;');
document.writeln('	padding-right:0;');
document.writeln('}');
document.writeln('.clear-padding-col{');
document.writeln('	padding-top:0;');
document.writeln('	padding-bottom:0;');
document.writeln('}');
document.writeln('.myfooter{');
document.writeln('	width: 100%;');
document.writeln('	padding-top: 10px;');
document.writeln('	padding-bottom: 10px;');
document.writeln('	background: #E7E7E7;');
document.writeln('}');
document.writeln('.copyright{');
document.writeln('	width: 100%;');
document.writeln('	margin: 0 auto;');
document.writeln('	color: #000000;');
document.writeln('	text-align: center;');
document.writeln('}');
document.writeln('.copyright img{');
document.writeln('	width: 30px;');
document.writeln('	height: 30px;');
document.writeln('}');
document.writeln('.copyright p{');
document.writeln('	font-size: 14px;');
document.writeln('}');
document.writeln('.fixed-footer{');
document.writeln('    position: fixed;');
document.writeln('	bottom: 0;');
document.writeln('}');
document.writeln('</style>');